import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
import { BASE_URL } from '../constants';

const baseQuery = fetchBaseQuery({ baseUrl: BASE_URL });

export const apiSlice = createApi({
  reducerPath: 'api', // optional but explicit
  baseQuery,
  tagTypes: ['Products', 'Orders', 'Users'],
  endpoints: (builder) => ({
    getProducts: builder.query({
      query: () => '/products', // adjust if your endpoint is different
    }),
  }),
});

// Export the hook generated by RTK Query
export const { useGetProductsQuery } = apiSlice;
